### ISSUE TITLE
Some commands fail with VALUE ERROR: Undefined name: Process

### ISSUE THREAD

**Issue by rikedyp** [aplteam/APLGit2#1] opened 2023-07-19 10:13 UTC
```
      ]APLGIT2.Version
0.15.1+216
      ]APLGIT2.ListBranches
* Command Execution Failed: VALUE ERROR: Undefined name: Process
```

**Comment by aplteam** [comment] 2023-07-19 11:23
Cannot reproduce on Windows, Linux, Mac OS.

**Comment by rikedyp** [comment] 2023-07-19 19:20
I just worked out it's .NET

APLGit2 works with .NET 4.8, but not with .NET 3.1 or 6.0

**Comment by aplteam** [comment] 2023-07-20 05:41
Fixed with v0.15.2 which does not use .NET at all anymore.

**Closed as completed by aplteam** 2023-07-20 05:41 UTC
